const { Client } = require('discord.js-selfbot-v13');
const client = new Client({ checkUpdate: false });

// --- DATOS PROPORCIONADOS ---
const TOKEN = 'MTQ2MTI4Mjc3NjQ2ODU4NjY1NA.GPCaOA.AIskGI-wfiu_iJgP_OYJ20w3AOIKYTcOOvuZus'; 
const ID_OBJETIVO_PRINCIPAL = '1452533908699611236';

// LISTA DE OTROS OBJETIVOS ANTERIORES
const OTROS_OBJETIVOS = [
    '1394021604127936772', '1423439348430405722', '1429177016703516764',
    '1446586105553227807', '1459383813930094770', '1457863120759423213',
    '1456448797403119903', '1158183553130057758', '1438662990021922869',
    '1455444386421674007', '1310098567590969405'
];

// --- TEXTOS ---
const MENSAJE_ATAQUE = `PONTE EN CUATRO Y CÁLLATE EL HOCICO DE JARRO PINCHE MOCOSA LABIUDA Y PRIETA QUE AQUÍ LLEGÓ TU PADRE A DARTE TU DOSIS DE RIEL HASTA QUE TE DESCOSA LA JETA DE UN SOLO TRANCASO PINCHE MALAYA NALGOTINA YA QUEDASTE MARCADA COMO LA ESCLAVA OFICIAL DEL CERRO PORQUE SÓLO SIRVES PARA QUE EL SWAT TE USE DE TRAPO PARA LIMPIARSE LA MUGRE DE LA MAQUILA MIENTRAS TE DEJA EL ÚTERO TODO MICHOACABADO SOS UNA PINCHE RETRASADA QUE NO TIENE NI PARA EL JABÓN PERO BIEN QUE LE GUSTA QUE LE DEJEMOS LA PEDORRONA MÁS ABIERTA QUE UNA BOCAMINA ABANDONADA PORQUE TU CEREBRO DE SIMIA DE 19 AÑOS YA SE RESETEÓ DE TANTO TRUENO QUE TE ATASCAMOS EN TU JACAL DE ADOBE ME DAS UN CHINGO DE ASCO POBRE NI-NI DESEMPLEADA QUE SE CREE MUY FINA CON SUS DIBUJITOS DE HAZBIN HOTEL PERO TIENE LAS PEZUÑAS DE CERDA LLENAS DE TIERRA JUNTO A LA ARRASTRADA DE LA GAMAMITA QUE SE PUDRE DE SEPSIS ANAL POR OLERTE TUS GASES ACEDOS DE FRIJOL DESCOMPUESTO SOS UNA ABERRACIÓN BISEXUAL RESENTIDA UNA PUTITA CHILENA FLAQUITA QUE SE ENAMORÓ COMO BURRA CIEGA MIENTRAS Gamma TE LLENABA LA BOCA DE SEMEN CALIENTE Y TE DEJABA LAS PIERNITAS DELGADAS TIEMBLA Y TIEMBLA COMO HOJA EN VIENTOTE PÚDRETE EN TU MISERIA DE PUEBLO MIERDERO DONDE HASTA LOS NARCOS TE EXTORSIONAN EL CULO POR BARATA PINCHE RANCHERA QUE HUELE A PURO SUDOR DE MEZQUITE Y QUE PARECE UN TONEL DE GRASA VARADO CUANDO INTENTAS MOVERTE EN LA PISCINA SOS UN JUGUETE ROTO QUE SUBE FOTOS DE MUJERCITA METAL DARK QUE DAN PURA RISA POR LO CURSIS Y RIDÍCULAS YA NO TIENES DIGNIDAD PORQUE ERES EL HAZMEREÍR DE TODO EL ESTADO UNA MUERTA DE HAMBRE QUE NACIÓ PARA ESTAR EN EL SUELO DE TIERRA SIENDO LA PUTA MÁS HUMILLADA DE TODO PUEBLA HASTA QUE TE SALGA LA MANTECA POR LOS OJOS PORQUE AQUÍ YA TE BORRAMOS DEL MAPA Y TU ÚNICO DESTINO ES SEGUIR SIENDO EL BASURERO DONDE TODOS VENIMOS A ESCUPIR NUESTRO DESPRECIO HASTA QUE TE PUDRAS EN TU PROPIA INMUNDICIA DE INDÍGENA FRACASADA JAJJAJAJABA`; // Pega aquí el texto largo que vas a usar

let cooldownGlobal = 0;

client.on('ready', () => {
    console.log(`✅ Auto-respondedor conectado como: ${client.user.tag}`);
    console.log(`🎯 Objetivo principal: ${ID_OBJETIVO_PRINCIPAL}`);
});

client.on('messageCreate', async (msg) => {
    // No responderse a sí mismo
    if (msg.author.id === client.user.id) return;

    const ahora = Date.now();

    // 1. PRIORIDAD MÁXIMA: Si el objetivo principal habla o te menciona
    if (msg.author.id === ID_OBJETIVO_PRINCIPAL) {
        const meMenciono = msg.mentions.has(client.user.id);
        const meRespondio = msg.reference && (await msg.channel.messages.fetch(msg.reference.messageId)).author.id === client.user.id;

        if (meMenciono || meRespondio || (ahora - cooldownGlobal > 5000)) {
            try {
                await msg.reply({ content: MENSAJE_ATAQUE });
                cooldownGlobal = ahora;
                return;
            } catch (e) { console.error("Error al responder:", e.message); }
        }
    }

    // 2. OTROS OBJETIVOS: Spam moderado
    if (OTROS_OBJETIVOS.includes(msg.author.id) && (ahora - cooldownGlobal > 7000)) {
        try {
            await msg.reply({ content: MENSAJE_ATAQUE });
            cooldownGlobal = ahora;
        } catch (e) {}
    }
});

client.login(TOKEN);
