github.com:
    users:
        R3X-source:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: R3X-source
